// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psaeaucivjwlmijtmqyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYWVhdWNpdmp3bG1panRtcXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjA3NTAsImV4cCI6MjA2OTAzNjc1MH0.TM8y6Q6uFRXQfT-13DEFEgZN7M58QvzsiYS5NjfJ_HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});